-- ============================================
-- NORMALIZED & SECURED DATABASE SCHEMA
-- For: infosec_lab (Student Management System)
-- ============================================
-- FIXES APPLIED:
-- 1. Normalized tables (courses separated from students)
-- 2. Foreign key constraints (referential integrity)
-- 3. Password stored as hash (VARCHAR 255 for bcrypt)
-- 4. Added user roles for access control
-- 5. Added login_attempts table for auditing
-- 6. Proper AUTO_INCREMENT and NOT NULL constraints
-- ============================================

DROP DATABASE IF EXISTS infosec_lab;
CREATE DATABASE infosec_lab;
USE infosec_lab;

-- ============================================
-- USERS TABLE (authentication + roles)
-- Password column is VARCHAR(255) for bcrypt hash
-- ============================================
CREATE TABLE `users` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `username` VARCHAR(50) NOT NULL UNIQUE,
    `password` VARCHAR(255) NOT NULL,
    `email` VARCHAR(100) NOT NULL UNIQUE,
    `role` ENUM('admin', 'user') NOT NULL DEFAULT 'user',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ============================================
-- COURSES TABLE (normalized from students)
-- Eliminates data redundancy: course + course_description
-- were previously duplicated per student row
-- ============================================
CREATE TABLE `courses` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `course_code` VARCHAR(50) NOT NULL UNIQUE,
    `course_description` VARCHAR(255) DEFAULT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ============================================
-- STUDENTS TABLE (with foreign key to courses)
-- References courses table instead of storing
-- course name and description redundantly
-- ============================================
CREATE TABLE `students` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `student_id` VARCHAR(50) NOT NULL UNIQUE,
    `fullname` VARCHAR(100) NOT NULL,
    `email` VARCHAR(100) NOT NULL,
    `course_id` INT(11) DEFAULT NULL,
    `created_by` INT(11) DEFAULT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`course_id`) REFERENCES `courses`(`id`) ON DELETE SET NULL,
    FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ============================================
-- LOGIN ATTEMPTS TABLE (security auditing)
-- Tracks all login attempts with IP address
-- ============================================
CREATE TABLE `login_attempts` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `username` VARCHAR(50) NOT NULL,
    `ip_address` VARCHAR(45) NOT NULL,
    `attempted_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `success` TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ============================================
-- INSERT DEFAULT ADMIN USER
-- Password: admin123 (hashed with password_hash)
-- Hash generated by: password_hash('admin123', PASSWORD_DEFAULT)
-- ============================================
INSERT INTO `users` (`username`, `password`, `email`, `role`) VALUES
('admin', '$2y$10$Ohpxkwg1Rx2eoR7oMqHus.q/ppCAxsOyvO5TLgfdGEkSD2pHRK.5.', 'admin@example.com', 'admin');

-- ============================================
-- INSERT SAMPLE COURSES
-- ============================================
INSERT INTO `courses` (`course_code`, `course_description`) VALUES
('BSIT', 'Bachelor of Science in Information Technology'),
('BSCS', 'Bachelor of Science in Computer Science'),
('BSIS', 'Bachelor of Science in Information Systems');

-- ============================================
-- BACKUP STRATEGY NOTES:
-- 1. Daily backup: mysqldump -u root infosec_lab > backup_YYYY-MM-DD.sql
-- 2. Store backups outside web root (e.g., C:\backups\)
-- 3. Retention: 7 daily, 4 weekly, 12 monthly
-- 4. Test restore monthly: mysql -u root infosec_lab < backup_file.sql
-- ============================================
